//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IDoTodayApiClient {

    /**
     * @return OK
     */
    getLists(): Promise<GetTaskListsResponse>;

    /**
     * @param body (optional) 
     * @return Created
     */
    createList(body: CreateTaskListRequest | undefined): Promise<CreateTaskListResponse>;

    /**
     * @return OK
     */
    getListById(id: number): Promise<GetTaskListResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    updateList(id: number, body: UpdateTaskListRequest | undefined): Promise<UpdateTaskListResponse>;

    /**
     * @return OK
     */
    deleteList(id: number): Promise<void>;

    /**
     * @param body (optional) 
     * @return Created
     */
    createTask(listId: number, body: CreateTaskRequest | undefined): Promise<CreateTaskResponse>;

    /**
     * @param body (optional) 
     * @return OK
     */
    updateTask(listId: number, taskId: number, body: UpdateTaskRequest | undefined): Promise<UpdateTaskResponse>;
}

export class DoTodayApiClient implements IDoTodayApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getLists(): Promise<GetTaskListsResponse> {
        let url_ = this.baseUrl + "/api/Lists";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLists(_response);
        });
    }

    protected processGetLists(response: Response): Promise<GetTaskListsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetTaskListsResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GetTaskListsResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    createList(body: CreateTaskListRequest | undefined): Promise<CreateTaskListResponse> {
        let url_ = this.baseUrl + "/api/Lists";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateList(_response);
        });
    }

    protected processCreateList(response: Response): Promise<CreateTaskListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CreateTaskListResponse.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateTaskListResponse>(null as any);
    }

    /**
     * @return OK
     */
    getListById(id: number): Promise<GetTaskListResponse> {
        let url_ = this.baseUrl + "/api/Lists/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetListById(_response);
        });
    }

    protected processGetListById(response: Response): Promise<GetTaskListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetTaskListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GetTaskListResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateList(id: number, body: UpdateTaskListRequest | undefined): Promise<UpdateTaskListResponse> {
        let url_ = this.baseUrl + "/api/Lists/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateList(_response);
        });
    }

    protected processUpdateList(response: Response): Promise<UpdateTaskListResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UpdateTaskListResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UpdateTaskListResponse>(null as any);
    }

    /**
     * @return OK
     */
    deleteList(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Lists/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteList(_response);
        });
    }

    protected processDeleteList(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    createTask(listId: number, body: CreateTaskRequest | undefined): Promise<CreateTaskResponse> {
        let url_ = this.baseUrl + "/api/lists/{listId}/Tasks";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateTask(_response);
        });
    }

    protected processCreateTask(response: Response): Promise<CreateTaskResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CreateTaskResponse.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateTaskResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateTask(listId: number, taskId: number, body: UpdateTaskRequest | undefined): Promise<UpdateTaskResponse> {
        let url_ = this.baseUrl + "/api/lists/{listId}/Tasks/{taskId}";
        if (listId === undefined || listId === null)
            throw new globalThis.Error("The parameter 'listId' must be defined.");
        url_ = url_.replace("{listId}", encodeURIComponent("" + listId));
        if (taskId === undefined || taskId === null)
            throw new globalThis.Error("The parameter 'taskId' must be defined.");
        url_ = url_.replace("{taskId}", encodeURIComponent("" + taskId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateTask(_response);
        });
    }

    protected processUpdateTask(response: Response): Promise<UpdateTaskResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UpdateTaskResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UpdateTaskResponse>(null as any);
    }
}

export class CreateTaskListRequest implements ICreateTaskListRequest {
    name!: string;

    constructor(data?: ICreateTaskListRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateTaskListRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTaskListRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateTaskListRequest {
    name: string;
}

export class CreateTaskListResponse implements ICreateTaskListResponse {
    list?: TaskListDto;

    constructor(data?: ICreateTaskListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.list = _data["list"] ? TaskListDto.fromJS(_data["list"]) : undefined as any;
        }
    }

    static fromJS(data: any): CreateTaskListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTaskListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["list"] = this.list ? this.list.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateTaskListResponse {
    list?: TaskListDto;
}

export class CreateTaskRequest implements ICreateTaskRequest {
    title!: string;

    constructor(data?: ICreateTaskRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
        }
    }

    static fromJS(data: any): CreateTaskRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTaskRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        return data;
    }
}

export interface ICreateTaskRequest {
    title: string;
}

export class CreateTaskResponse implements ICreateTaskResponse {
    task?: TaskDto;

    constructor(data?: ICreateTaskResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.task = _data["task"] ? TaskDto.fromJS(_data["task"]) : undefined as any;
        }
    }

    static fromJS(data: any): CreateTaskResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTaskResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["task"] = this.task ? this.task.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateTaskResponse {
    task?: TaskDto;
}

export class GetTaskListResponse implements IGetTaskListResponse {
    list?: TaskListDto;

    constructor(data?: IGetTaskListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.list = _data["list"] ? TaskListDto.fromJS(_data["list"]) : undefined as any;
        }
    }

    static fromJS(data: any): GetTaskListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetTaskListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["list"] = this.list ? this.list.toJSON() : undefined as any;
        return data;
    }
}

export interface IGetTaskListResponse {
    list?: TaskListDto;
}

export class GetTaskListsResponse implements IGetTaskListsResponse {
    lists?: TaskListSummaryDto[] | undefined;

    constructor(data?: IGetTaskListsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["lists"])) {
                this.lists = [] as any;
                for (let item of _data["lists"])
                    this.lists!.push(TaskListSummaryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetTaskListsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetTaskListsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.lists)) {
            data["lists"] = [];
            for (let item of this.lists)
                data["lists"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IGetTaskListsResponse {
    lists?: TaskListSummaryDto[] | undefined;
}

export class TaskDto implements ITaskDto {
    id?: number;
    title?: string | undefined;
    isCompleted?: boolean;
    listId?: number;

    constructor(data?: ITaskDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.isCompleted = _data["isCompleted"];
            this.listId = _data["listId"];
        }
    }

    static fromJS(data: any): TaskDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaskDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["isCompleted"] = this.isCompleted;
        data["listId"] = this.listId;
        return data;
    }
}

export interface ITaskDto {
    id?: number;
    title?: string | undefined;
    isCompleted?: boolean;
    listId?: number;
}

export class TaskListDto implements ITaskListDto {
    id?: number;
    name?: string | undefined;
    tasks?: TaskDto[] | undefined;

    constructor(data?: ITaskListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            if (Array.isArray(_data["tasks"])) {
                this.tasks = [] as any;
                for (let item of _data["tasks"])
                    this.tasks!.push(TaskDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TaskListDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaskListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        if (Array.isArray(this.tasks)) {
            data["tasks"] = [];
            for (let item of this.tasks)
                data["tasks"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ITaskListDto {
    id?: number;
    name?: string | undefined;
    tasks?: TaskDto[] | undefined;
}

export class TaskListSummaryDto implements ITaskListSummaryDto {
    id?: number;
    name?: string | undefined;

    constructor(data?: ITaskListSummaryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): TaskListSummaryDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaskListSummaryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface ITaskListSummaryDto {
    id?: number;
    name?: string | undefined;
}

export class UpdateTaskListRequest implements IUpdateTaskListRequest {
    name?: string | undefined;

    constructor(data?: IUpdateTaskListRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): UpdateTaskListRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTaskListRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface IUpdateTaskListRequest {
    name?: string | undefined;
}

export class UpdateTaskListResponse implements IUpdateTaskListResponse {
    list?: TaskListDto;

    constructor(data?: IUpdateTaskListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.list = _data["list"] ? TaskListDto.fromJS(_data["list"]) : undefined as any;
        }
    }

    static fromJS(data: any): UpdateTaskListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTaskListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["list"] = this.list ? this.list.toJSON() : undefined as any;
        return data;
    }
}

export interface IUpdateTaskListResponse {
    list?: TaskListDto;
}

export class UpdateTaskRequest implements IUpdateTaskRequest {
    isCompleted?: boolean | undefined;

    constructor(data?: IUpdateTaskRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isCompleted = _data["isCompleted"];
        }
    }

    static fromJS(data: any): UpdateTaskRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTaskRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isCompleted"] = this.isCompleted;
        return data;
    }
}

export interface IUpdateTaskRequest {
    isCompleted?: boolean | undefined;
}

export class UpdateTaskResponse implements IUpdateTaskResponse {
    task?: TaskDto;

    constructor(data?: IUpdateTaskResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.task = _data["task"] ? TaskDto.fromJS(_data["task"]) : undefined as any;
        }
    }

    static fromJS(data: any): UpdateTaskResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTaskResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["task"] = this.task ? this.task.toJSON() : undefined as any;
        return data;
    }
}

export interface IUpdateTaskResponse {
    task?: TaskDto;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}